#!/bin/sh
log "Starting S07-medium..."
log "======================"

#=============================================
# 11) check medium related install.inf vars
#---------------------------------------------
Y2_NETWORK_ACTIVE=0
Y2_SSH_ACTIVE=0
log "\tChecking kernel commandline..."
#=============================================
# 11.1 start shell on second virtual console
#---------------------------------------------
if ! got_install_param '^NoShell:.*1' ; then
        log "\tGot kernel parameter <NoShell> -> start shell on tty2"
        SPID=`/usr/lib/YaST2/bin/startshell /dev/tty2`
fi

#=============================================
# 11.1) activate network if configuration found
#---------------------------------------------
if [ ! -z $(ls /etc/sysconfig/network/ifcfg-* |grep  -v 'ifcfg-lo') ] ;then
	log "\tnetwork configuration found -> activate network"
	rcnetwork start && Y2_NETWORK_ACTIVE=1

# firewall is started by rcnetwork
#	rcSuSEfirewall2 reload


# if nfs:// is used for install source or add-on (reminder /var/lib/YaST2/network_install_portmap),
#	start rcportmap

[ -f /var/lib/YaST2/network_install_portmap ] && rcportmap start

fi
if got_install_param '^UseSSH:.*1' ; then
	log "\tGot kernel parameter UseSSH -> export UseSSH variable"
	rcsshd start    && Y2_SSH_ACTIVE=1
fi
log "\tSummary for commandline checks:"
log "\tY2_NETWORK_ACTIVE = $Y2_NETWORK_ACTIVE"
log "\tY2_SSH_ACTIVE     = $Y2_SSH_ACTIVE"
