#!/bin/sh
log "Starting F03-umount..."
log "======================"

#================================================
# 3) try to umount inst-sys and save exit status
#------------------------------------------------
umount /var/adm/mount &>/dev/null
umount_exit=$?
echo "umount_result: $umount_exit" >> /etc/install.inf
log "\tTrying to umount inst-sys exits with code: $umount_exit"
