#!/bin/sh
log "Starting F03-language..."
log "========================"

#=============================================
# 3) set language environment
#---------------------------------------------
LANGUAGE=en_US
infofile=/content
if [ -f $infofile ];then
	LANGUAGE=`sed -n 's/^LANGUAGE \([^ ]*\)/\1/p' $infofile`
fi
if [ ! "$Locale" = "" ];then
	LANGUAGE=$Locale
fi
set_language_init
umount /var/adm/mount &>/dev/null
log "\tLanguage set to: $LANG"

#=============================================
# 3.1) start unicode mode
#---------------------------------------------
export LANG
start_unicode
