#!/bin/sh
log "Starting F04-cmdline..."
log "======================="

#=============================================
# 4) check proc/cmdline parameters
#---------------------------------------------
# 4.1) check for repair parameter...
if got_kernel_param "repair" ; then
	log "\tGot kernel parameter: <repair> -> saving to install.inf"
	echo "Repair: true" >> /etc/install.inf
fi
