#!/bin/sh
log "Starting F05-terminal..."
log "========================"

#=============================================
# 5) setup TERM variable
#---------------------------------------------
if [ ! -z "$Console" ] && [ "$TERM" != "linux" ] ; then
	eval `initviocons -e`
	export LINES COLUMNS TERM
	log "\tSetup virtual console:"
	log "\tLines:   $LINES"
	log "\tColumns: $COLUMNS"
	log "\tType:    $TERM"

	log "\tAsking for Serial console type..."
	set_term_variable
	log "\tType:    $TERM"
fi
