#!/bin/sh
log "Starting F06-config..."
log "======================"

#=============================================
# 6) create /etc/mtab
#---------------------------------------------
log "\tCreating /etc/mtab"
cp -f /proc/mounts /etc/mtab
