#!/bin/sh
log "Starting F07-logging..."
log "======================="

#=============================================
# 7) setup default logfile size
#---------------------------------------------
test -z "$Y2MAXLOGSIZE" && export Y2MAXLOGSIZE=100
test -z "$Y2MAXLOGNUM"  && export Y2MAXLOGNUM=5

#=============================================
# 7.1) setup logfile size as 1/3 of FreeRam
#---------------------------------------------
USE=`awk '/^MemFree:/{ n=2 ; printf "%d\n", $n/3 }' /proc/meminfo`
if [ "$USE" -gt "$Y2MAXLOGSIZE" ];then
	export Y2MAXLOGSIZE=$USE
fi

#=============================================
# 7.2) report used logfile size and lognum
#---------------------------------------------
log "\tSet YaST2 LOG parameters:"
log "\tMaximum log size:  $Y2MAXLOGSIZE Kb"
log "\tMaximum log count: $Y2MAXLOGNUM"
