#!/bin/sh
log "Starting F07-logging..."
log "======================="

#=============================================
# 7) setup logfile size
#---------------------------------------------
test -z "$Y2MAXLOGSIZE" && export Y2MAXLOGSIZE=100
test -z "$Y2MAXLOGNUM"  && export Y2MAXLOGNUM=5
log "\tSet YaST2 LOG parameters:"
log "\tMaximum log size:  $Y2MAXLOGSIZE"
log "\tMaximum log count: $Y2MAXLOGNUM"
