#!/bin/sh
log "Starting F08-logging..."
log "======================="

#=============================================
# 8) setup default logfile size
#---------------------------------------------

# log size defined by user
Y2MAXLOGSIZE_INITIAL=$Y2MAXLOGSIZE

test -z "$Y2MAXLOGSIZE" && export Y2MAXLOGSIZE=100
test -z "$Y2MAXLOGNUM"  && export Y2MAXLOGNUM=5

#=============================================
# 8.1) setup logfile size as 1/3 of FreeRam
#---------------------------------------------

# log size not defined by user
if [ "$Y2MAXLOGSIZE_INITIAL" == "" ]; then
    USE=`awk '/^MemFree:/{ n=2 ; printf "%d\n", $n/3 }' /proc/meminfo`
    if [ "$USE" -gt "$Y2MAXLOGSIZE" ];then
	    export Y2MAXLOGSIZE=$USE
    fi
fi

# fate#302166: store y2debug messages and log them on crash
export Y2DEBUGONCRASH=1

#=============================================
# 8.2) report used logfile size and lognum
#---------------------------------------------
log "\tSet YaST2 LOG parameters:"
log "\tMaximum log size:  $Y2MAXLOGSIZE Kb"
log "\tMaximum log count: $Y2MAXLOGNUM"
