#!/bin/sh
log "Starting F02-hwinfo..."
log "======================"

#=============================================
# 2) start hardware detection
#---------------------------------------------
HOSTTYPE=`uname -m`
log "\tHardware detection for arch: $HOSTTYPE"
case "$HOSTTYPE" in
	s390|s390x)
	# s390/s390x architectures...
	;;
	ppc*)
	# ppc architecture...
	/usr/sbin/hwinfo --special=x11
	;;
	*)
	# all other architectures...
	/usr/sbin/hwinfo --special=braille
	/usr/sbin/hwinfo --special=x11
esac

#=============================================
# 2.1) set splash progress bar to 80%
#---------------------------------------------
set_splash 80
