#!/bin/sh
log "Starting F08-start..."
log "====================="

#=============================================
# 8) call preFirstCall hook scripts
#---------------------------------------------
callHooks preFirstCall

#=============================================
# 8.1) goto run stage, start YaST2 (initial)
#---------------------------------------------
rm -f /var/X11R6/bin/X
rm -f /tmp/YaST2_ssh_installation_finished
log "\tDelegate program call to YaST2.call installation initial"
/usr/lib/YaST2/startup/YaST2.call installation initial
yast2exitcode=$?

#=============================================
# 8.2) save log file to installed system
#---------------------------------------------
log "\tCopy first level log file to installed system"
mkdir -p /mnt/var/log/YaST2
cp /var/log/YaST2/y2start.log /mnt/var/log/YaST2

#=============================================
# 8.3) call postFirstCall hook scripts
#---------------------------------------------
callHooks postFirstCall
