#!/bin/sh
#================
# FILE          : requires
#----------------
# PROJECT       : YaST (Yet another Setup Tool v2)
# COPYRIGHT     : (c) 2004 SUSE Linux AG, Germany. All rights reserved
#               :
# AUTHORS       : Marcus Schaefer <ms@suse.de>
#               :
#               :
# BELONGS TO    : System installation and Administration
#               :
# DESCRIPTION   : This file contains all information describing
#               : the various requirements which needs to be fulfilled
#               : 
#               :
# STATUS        : $Id$
#----------------
#
#=========================================
# min. memory needed for installation
#-----------------------------------------
MEM_NEEDED=90000
