#!/bin/sh

PATH=$PATH:/usr/lib/YaST2/bin
cd /usr/lib/YaST2/clients
/usr/lib/YaST2/bin/y2base menu '("test")' qt -geometry 800x600 -style=platinum -font '-gnu-unifont-medium-r-normal--16-160-75-75-p-80-iso10646-1'
