#!/bin/sh

PATH=$PATH:/usr/lib/YaST2/bin
cd /usr/share/YaST2/clients

if [ "$DISPLAY" ]; then
  y2base installation '("screenshots")' '("initial")' qt -geometry 800x600 -style=platinum -font '-gnu-unifont-medium-r-normal--16-160-75-75-p-80-iso10646-1' -bg grey80
else
  y2base installation '("screenshots")' '("initial")' ncurses
fi

# watch 'ls -rlt /tmp/scr*.png 2>/dev/null'
