#!/bin/sh

PATH=$PATH:/usr/lib/YaST2/bin
cd /usr/share/YaST2/clients

if [ "$DISPLAY" ]; then
  y2base installation '("screenshots")' '("continue")' qt -geometry 800x600 -style=platinum -bg grey80
else
  y2base installation '("screenshots")' '("continue")' ncurses
fi
