#!/bin/sh
log "Starting S03-autoconf..."
log "========================"

#=============================================
# 4) check for control file and start
#---------------------------------------------
if [ -r /var/lib/autoinstall/autoconf/autoconf.xml ]; then
	log "\tFound autoconf.xml file, starting YaST..."
	startYaST2 ; exit 0
fi
